# Naming conventions:
#
# fl - front left  | fr - front right
# cl - center left | cr - center right
# rl - rear left   | rr - rear right

# Pin numbers for motors on PWM board
pin_drive_fl: 9
pin_steer_fl: 11

pin_drive_fr: 7
pin_steer_fr: 4

pin_drive_cl: 8
pin_steer_cl: 10

pin_drive_cr: 6
pin_steer_cr: 5

pin_drive_rl: 0
pin_steer_rl: 2

pin_drive_rr: 1
pin_steer_rr: 3

## PWM values
# Those values highly depend on the motors and pwm board used
# Check out the wiki for further explanation

# PWM values for the neutral steering position

steer_pwm_neutral_fl: 4456
steer_pwm_neutral_fr: 4481
steer_pwm_neutral_cl: 4451
steer_pwm_neutral_cr: 4601
steer_pwm_neutral_rl: 4511
steer_pwm_neutral_rr: 4331

# PWW range around steering neutral position
steer_pwm_range: 5734

# PWM value for the stop position of driving motors
drive_pwm_neutral: 4915

# PWW range around driving neutral position
drive_pwm_range: 5734
